jobs:
  include:
  - stage: test
    language: node_js
    cache: npm
    node_js:
      - 10.16.1
    after_success:
      - npm run codecov
    on:
      tags: false

  - stage: docker
    if: NOT type = pull_request AND branch = develop
    sudo: required
    services:
    - docker
    language: bash
    on:
      tags: false
    script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build --build-arg NODE_ENV=production -t eiabea/tempea-api:arm-develop .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push eiabea/tempea-api:arm-develop

  - stage: docker
    if: NOT type = pull_request AND branch = master
    sudo: required
    services:
    - docker
    language: bash
    on:
      tags: false
    script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build --build-arg NODE_ENV=production -t eiabea/tempea-api:arm-latest .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push eiabea/tempea-api:arm-latest

  - stage: docker
    sudo: required
    if: NOT type = pull_request AND tag IS present 
    services:
    - docker
    language: bash
    on:
      tags: true
    script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build --build-arg NODE_ENV=production -t eiabea/tempea-api:arm-"$TRAVIS_TAG" .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push eiabea/tempea-api:arm-"$TRAVIS_TAG"
