jobs:
  include:
  - stage: test
    language: node_js
    cache: npm
    node_js:
      - 10.14.0
    after_success:
      - npm run codecov
    on:
      tags: false

  - stage: docker
    if: NOT type = pull_request AND branch = master
    sudo: required
    services:
    - docker
    language: bash
    on:
      tags: false
    script:
    - >
      docker run --rm --privileged multiarch/qemu-user-static:register --reset
      docker build -t eiabea/tempea-api:arm-latest .
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push eiabea/tempea-api:arm-latest

  - stage: docker
    sudo: required
    if: NOT type = pull_request AND tag IS present 
    services:
    - docker
    language: bash
    on:
      tags: true
    script:
    - >
      if [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        docker build -t eiabea/tempea-api:arm-"$TRAVIS_TAG" .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push eiabea/tempea-api:arm-"$TRAVIS_TAG"
      fi
