jobs:
  include:
  - stage: test
    language: node_js
    node_js:
    - 9.11.2
    after_success:
    - npm run coveralls
  - stage: docker
    sudo: required
    services:
    - docker
    language: bash
    if: branch = master AND type != pull_request
    script:
    - >
      docker run --rm --privileged multiarch/qemu-user-static:register --reset
      docker build -t eiabea/tempea-api:arm-latest .
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push eiabea/tempea-api:arm-latest
