version: "3"

services:
  tempea:
    build: "."
    privileged: "true"
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
    environment:
      # Logging
      LOG_SRC: "true"
      LOG_LEVEL_STDOUT: "trace"
      LOG_LEVEL_GRAYLOG: "info"
      LOG_GRAYLOG_ENABLED: "false"
      # Modules
      ROUTING_MODULE_HOST: "0.0.0.0"
      ROUTING_MODULE_PORT: "3000"

      SENSOR_ID: "10-0008032d5234"
      # Celius (float)
      MAX_TEMP: "27"
      MIN_TEMP: "15"
      OVERSHOOT_TEMP: "0"
      # Minutes
      FETCHING_INTERVAL: "10"