version: "3"

volumes:
  mqtt:
    driver: "local"
  influx:
    driver: "local"
  grafana:
    driver: "local"

services:
  grafana:
    image: "grafana/grafana:5.4.3"
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - "grafana:/var/lib/grafana"
      
  mqtt:
    image: "eclipse-mosquitto:1.6.7"
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mqtt:/mosquitto/data"

  telegraf:
    image: "telegraf:1.12.4"
    restart: unless-stopped
    depends_on:
      - "mqtt"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  influx:
    image: "arm32v7/influxdb:1.7.8"
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - "influx:/var/lib/influxdb"

  tempea:
    image: "eiabea/tempea-api:arm-latest"
    restart: unless-stopped
    privileged: "true"
    command: "npm run start"
    depends_on:
      - "influx"
    ports:
      - "3000:3000"
    volumes:
      - "./secrets:/src/secrets"
    command: [ 
      "wait-for-it.sh", "influx:8086","--timeout=60", "--",
      "npm", "start"
    ]
    env_file:
      - tempea.env
