version: "3"

volumes:
  mqtt:
    driver: "local"
  influx:
    driver: "local"

services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3001:3000"
      
  mqtt:
    image: "eclipse-mosquitto:1.5.5"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mqtt:/mosquitto/data"

  telegraf:
    image: "telegraf:1.9.2"
    depends_on:
      - "mqtt"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  influx:
    image: "arm32v7/influxdb"
    ports:
      - "8086:8086"
    volumes:
      - "influx:/var/lib/influxdb"

  tempea:
    build: "."
    privileged: "true"
    command: "npm run start:dev:pretty"
    depends_on:
      - "influx"
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
    environment:
      # Google
      GOOGLE_SERVICE_ACCOUNT_JSON: "tempea-service.json"
      GOOGLE_CALENDAR_ID: "developer@eiabea.com"
      # Modules
      ROUTING_MODULE_HOST: "0.0.0.0"
      ROUTING_MODULE_PORT: "3000"
      # Database
      #  Influx
      INFLUX_HOST: "influx"
      INFLUX_PORT: "8086"
      INFLUX_DB: "temp"
      # Hardware
      SENSOR_ID: "10-00080278b776"
      # Slave
      SLAVE_ENABLED: "true"
      SLAVE_HOST: "192.168.0.7"
      SLAVE_PORT: "3000"
      SLAVE_ENDPOINT: "/v1/status"
      # Celius (float)
      MAX_TEMP: "25"
      MIN_TEMP: "15"
      OVERSHOOT_TEMP: "0.5"
      # Minutes
      FETCHING_INTERVAL: "1"
