version: "3"

volumes:
  influx:
    driver: "local"
  redis:
    driver: "local"

services:
  influx:
    image: "arm32v7/influxdb"
    ports:
      - "8086:8086"
    volumes:
      - "influx:/var/lib/influxdb"

  redis:
    image: "arm32v7/redis"
    command: "redis-server --appendonly yes"
    volumes:
      - "redis:/data"

  tempea:
    build: "."
    privileged: "true"
    depends_on:
      - "influx"
      - "redis"
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
    environment:
      # Logging
      LOG_SRC: "true"
      LOG_LEVEL_STDOUT: "trace"
      LOG_LEVEL_GRAYLOG: "info"
      LOG_GRAYLOG_ENABLED: "false"
      # Modules
      ROUTING_MODULE_HOST: "0.0.0.0"
      ROUTING_MODULE_PORT: "3000"
      # Database
      INFLUX_HOST: "influx"
      INFLUX_PORT: "8086"
      INFLUX_DB: "temp"

      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

      SENSOR_ID: "10-0008032d5234"
      # Celius (float)
      MAX_TEMP: "25"
      MIN_TEMP: "15"
      OVERSHOOT_TEMP: "0.5"
      # Minutes
      FETCHING_INTERVAL: "1"
