version: "3"

volumes:
  influx:
    driver: "local"

services:
  influx:
    image: "arm32v7/influxdb"
    ports:
      - "8086:8086"
    volumes:
      - "influx:/var/lib/influxdb"

  tempea:
    image: "eiabea/tempea-api:arm-latest"
    privileged: "true"
    depends_on:
      - "influx"
    ports:
      - "3000:3000"
    volumes:
      - "./secrets:/src/secrets"
    command: [ 
      "wait-for-it.sh", "influx:8086","--timeout=60", "--",
      "npm", "start"
    ]
    environment:
      # Google
      GOOGLE_SERVICE_ACCOUNT_JSON: "tempea-service.json"
      GOOGLE_CALENDAR_ID: "developer@eiabea.com"
      # Modules
      ROUTING_MODULE_HOST: "0.0.0.0"
      ROUTING_MODULE_PORT: "3000"
      # Database
      #  Influx
      INFLUX_HOST: "influx"
      INFLUX_PORT: "8086"
      INFLUX_DB: "temp"
      # Hardware
      SENSOR_ID: "10-00080278b776"
      # Slave
      SLAVE_ENABLED: "true"
      SLAVE_HOST: "192.168.0.7"
      SLAVE_PORT: "3000"
      SLAVE_ENDPOINT: "/v1/status"
      # Celius (float)
      MAX_TEMP: "25"
      MIN_TEMP: "15"
      OVERSHOOT_TEMP: "0.5"
      # Minutes
      FETCHING_INTERVAL: "1"
